### PR TITLE
Fix checksum logic in `pelican object stat`

### LINKED ISSUE #2827: pelican stat obj --checksums sha returns MD5
Pelican Version:
```
$ /usr/bin/pelican --version
Version: 7.21.1
Build Date: 2025-11-12T17:57:23Z
Build Commit: be4219df1f4be07a3e2bbf8d8f33f613d6792914
Built By: goreleaser
```

Pelican Service:
- [x] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [ ] Origin
- [ ] Cache
- [ ] Other (please give the detail)

**Describe the bug**

A pelican CLI request for an object SHA checksum returns MD5 instead.

**To Reproduce**

```
$ /usr/bin/pelican object stat osdf:///gwdata/O1/strain.4k/frame.v1/H1/1126170624/H-H1_LOSC_4_V1-1126256640-4096.gwf --checksums sha
Name: /gwdata/O1/strain.4k/frame.v1/H1/1126170624/H-H1_LOSC_4_V1-1126256640-4096.gwf
Size: 130071049
ModTime: 2018-01-12 23:33:08 +0000 GMT
IsCollection: false
Checksums:
  md5: 4515e676e0d4c5be7298609bc04eea20
```

**Expected behavior**

This should have returned the SHA checksum and not the MD5 returned by,
```
$ /usr/bin/pelican object stat osdf:///gwdata/O1/strain.4k/frame.v1/H1/1126170624/H-H1_LOSC_4_V1-1126256640-4096.gwf --checksums md5
Name: /gwdata/O1/strain.4k/frame.v1/H1/1126170624/H-H1_LOSC_4_V1-1126256640-4096.gwf
Size: 130071049
ModTime: 2018-01-12 23:33:08 +0000 GMT
IsCollection: false
Checksums:
  md5: 4515e676e0d4c5be7298609bc04eea20
```

**Desktop (please complete the following information):**
 - OS: **AlmaLinux 10.1**

**Additional context**

For bonus points clarify which Specific  SHA checksum the string "sha" refers to, e.g., SHA256 vs SAH3-256 vs ...

### PR DESCRIPTION
**Pull request by patrickbrophy**
Fixes #2827. When running `pelican object stat --checksums sha`, the client would display what checksum the server returned without any indication that the requested checksum type wasn't provided. Now we track the requested checksums and track that they are satisfied. We now log a warning when the requested checksum types are not returned by the server.

### CODE REVIEW

File: client/main.go [hunk 1]
```diff
@@ -216,22 +217,58 @@ func DoStat(ctx context.Context, destination string, options ...TransferOption)
...
-				statInfo.Checksums[HttpDigestFromChecksum(info.Algorithm)] = hex.EncodeToString(info.Value)
+				digestName := HttpDigestFromChecksum(info.Algorithm)
+				if digestName == "" {
+					continue
+				}
+				statInfo.Checksums[digestName] = hex.EncodeToString(info.Value)
+				delete(remaining, info.Algorithm)
+				collected = true
+			}
+			if len(remaining) == 0 {
```
Comment (turetske) [inline client/main.go]: Just to clarify more my own understanding, since you only delete info.Algorithm from remaining when there is no checksumErr, this is only true if all the checksums have evaluated with no error?

File: client/main.go [hunk 2]
```diff
@@ -216,22 +217,58 @@ func DoStat(ctx context.Context, destination string, options ...TransferOption)
...
+				break
 			}
 		}
-		if lastErr != nil {
-			err = errors.Wrap(lastErr, "failed to fetch checksums")
+		if !collected {
+			if checksumErr == nil {
+				checksumErr = errors.New("no checksum data returned by server")
+			}
+			err = errors.Wrap(checksumErr, "failed to fetch checksums")
```
Comment (turetske) [inline client/main.go]: Will this mean if the server doesn't have checksumming, this will throw an error? Or is there a check higher up in the algorithm I can't see due to the nature of the PR

**Review by turetske — APPROVED** [review]
LGTM!
