### PR TITLE
Fix Config Bug

### LINKED ISSUE #380: Config page breaks on receiving a null value
Currently config page content breaks when there is a null value in the config response.

### PR DESCRIPTION
**Pull request by CannonLock**
- Add strong typing to avoid future bugs
- Add null, string[] and int[] support

Fixes #380

### CODE REVIEW

File: origin_ui/src/app/(dashboard)/config/page.tsx [hunk 1]
```diff
@@ -35,100 +35,21 @@ import {isLoggedIn} from "@/helpers/login";
...
-        PortLower: number;
-        PortHigher: number;
-    };
+type Config = {
+    [key: string]: ConfigValue
 }
 
-function sortConfig (a: any, b: any) {
-    if(typeof a[1] == 'object' && typeof b[1] != 'object'){
+type ConfigValue = Config | string | number | boolean | null | string[] | number[] | duration
```
Comment (haoming29) [inline origin_ui/src/app/(dashboard)/config/page.tsx:42]: Thanks for making this change! It will be greatly improve the robustness of the way we displaying config values

**Review by haoming29 — APPROVED** [review]
LGTM! Manually added a new config locally and the `/config` page still works as expected. Thanks for making this so flexible!
