### PR TITLE
Exit main process if error group goroutine returns error

### LINKED ISSUE #661: Cache: deal with xrootd processes dying
The xrootd process on my cache (started with `osdf cache serve`) crashed:
```
Jan 13 21:01:30 sc-cache.chtc.wisc.edu osdf[7861]: time="2024-01-13T21:01:29-06:00" level=error msg="xrootd process failed unexpectedly: signal: segmentation fault"
```
The osdf process neither exited nor did it attempt to restart xrootd. In case xrootd crashes, Pelican should exit with an error; the service manager (systemd or supervisord) will take care of restarting it if it's configured to do so.

### PR DESCRIPTION
**Pull request by haoming29**
Fixes #661 
* Fix the issue where Pelican won'y exit main process if error group goroutine returns error, unless an error returns in the main goroutine
* Fix the panic at the director when a cache advertise itself to the director, as we didn't have the case for cache when doing version compatibility check
* Improve logging at program exit to be consistent.
* Improve cache error group, remove duplicated exit handler that `root.go` already had.

~~However, this didn't fix the issue where when we exit the program with `ctrl+c` , xrootd reported error as it treated SIGINT similar as SIGSEGV. We might have to refactor some of the code in `daemon/launch_unix.go`. Created a separate issue for this: #672~~

### CODE REVIEW

**Review by matyasselmeci — COMMENTED** [review]
Some tweaks; also the changes in `director/redirect.go` seem unrelated to this issue and should be in a separate PR.

File: cmd/cache_serve.go [hunk 1]
```diff
@@ -146,43 +127,44 @@ func serveCacheInternal(ctx context.Context) error {
...
-	go func() {
-		if err := web_ui.RunEngine(ctx, engine, egrp); err != nil {
-			log.Panicln("Failure when running the web engine:", err)
+	egrp.Go(func() error {
+		if err := web_ui.RunEngine(cmdCtx, engine, egrp); err != nil {
+			log.Errorln("Failure when running the web engine:", err)
+			return err
+		} else {
+			return err
 		}
```
[the remark this answers is not in the document]
Comment (bbockelm) [reply cmd/cache_serve.go:140]: That refactor has slightly different semantics.

In the original, the `err` object is local to the conditional block.

In your refactor, it uses the `err` object from the containing function, meaning that multiple routines might be using the same object at the same time, resulting in a potential (but admittedly unlikely) race condition).

One could do this:

```
	egrp.Go(func() (err error) {
		if err = web_ui.RunEngine(cmdCtx, engine, egrp); err != nil {
			log.Errorln("Failure when running the web engine:", err)
		}
		return err
	})
```

File: cmd/cache_serve.go [hunk 2]
```diff
@@ -146,43 +127,44 @@ func serveCacheInternal(ctx context.Context) error {
...
-		shutdownCancel()
```
Comment (bbockelm) [inline cmd/cache_serve.go:157]: This cancel (and the equivalent one in launchers) needs to be kept around.

The web engine may fail to startup and this `shutdownCancel()` call may be the thing that triggers the shutdown originally.

File: cmd/root.go [hunk 3]
```diff
@@ -78,18 +78,17 @@ func (i *uint16Value) Type() string {
...
+	egrp, egrpCtx := errgroup.WithContext(context.Background())
 	defer func() {
 		err := egrp.Wait()
 		if err != nil {
-			if err.Error() == "Federation process has been cancelled" {
-				log.Info("Process was shutdown")
-				return
-			}
-			log.Errorln("Error occurred when shutting down process:", err)
+			log.Errorln("Fatal error occured that leads to shutdown of the process:", err)
```
Comment (bbockelm) [inline cmd/root.go:85]:
```suggestion
			log.Errorln("Fatal error occurred that lead to the shutdown of the process:", err)
```

File: cmd/cache_serve.go [hunk 4]
```diff
@@ -85,33 +82,17 @@ func serveCache(cmd *cobra.Command, _ []string) error {
...
+	err := config.InitServer(cmdCtx, config.CacheType)
 	cobra.CheckErr(err)
 
-	egrp, ok := ctx.Value(config.EgrpKey).(*errgroup.Group)
+	egrp, ok := cmdCtx.Value(config.EgrpKey).(*errgroup.Group)
 	if !ok {
 		egrp = &errgroup.Group{}
 	}
 
-	egrp.Go(func() error {
```
Comment (bbockelm) [inline cmd/cache_serve.go:100]: I don't like removing the signal handler from here.  It means that the only way signals are propagated to shutdown Pelican are when xrootd has already been started, pelican forwards the signal to xrootd, and xrootd decides to shutdown.  That's a fairly brittle combination.

File: cmd/root.go [hunk 5]
```diff
@@ -78,18 +78,17 @@ func (i *uint16Value) Type() string {
...
+		} else {
+			// Use Error instead of Info because our default log level is Error
+			log.Error("Pelican is safely exited")
 		}
 	}()
-	ctx := context.WithValue(context.Background(), config.EgrpKey, &egrp)
+	ctx := context.WithValue(egrpCtx, config.EgrpKey, egrp)
 	return rootCmd.ExecuteContext(ctx)
```
Comment (bbockelm) [inline cmd/root.go:92]: This is a related bug (not caused by your PR but made it obvious).

If `serveCache` fails with an error (that is, the cache fails to startup), then nothing cancels the context, causing the process to hang indefinitely.

Contrast this to the `serveOrigin` process which wraps everything with a non-nil-error check:

```
func serveOrigin(cmd *cobra.Command, args []string) error {
	cancel, err := launchers.LaunchModules(cmd.Context(), config.OriginType)
	if err != nil {
		cancel()
	}

	return err
}
```

We either want to wrap `cacheServe` similarly or hoist the cancelation all the way up to here.

File: cmd/cache_serve.go (hunk 4 above)
Comment (haoming29) [reply cmd/cache_serve.go:100]: I thought we had this logic in `cmd/root.go` which is global to all commands we run. Isn't here a duplicated code?

Comment (haoming29) [reply cmd/cache_serve.go:100]: No you are right. I got myself confused by the one in the `launcher.go` but cache wasn't launched by that route.

File: cmd/cache_serve.go (hunk 2 above)
Comment (turetske) [reply cmd/cache_serve.go:157]: @haoming29 Waiting on @bbockelm to answer this before I do my review, as this was my only concern as well.

**Review by bbockelm — APPROVED** [review]
LGTM with latest revisions.

@joereuss12 - I believe you were the 7.4.0 release manager, right?  If so, can you please backport this PR to that branch and do a bugfix release for @matyasselmeci?

**Comment by joereuss12** [comment]
Just cut a bugfix release!
