### PR TITLE
Fix origin registration status not updated

### LINKED ISSUE #1229: Origin registration status API doesn't update
Pelican Version:
_Run `./pelican --version` to get version number._

Pelican Service:
- Origin

**Describe the bug**
_A clear and concise description of what the bug is._

The `/origin_ui/exports` API contains origin registration status. The data should reflect if the origin registration is complete. However, even after the admin fixed the issue at the registry, the API still returns the existing status and didn't pull the latest status.

### PR DESCRIPTION
**Pull request by haoming29**
Fixes #1229 

@CannonLock requested your review since you have the frontend set up to check this. Even with the fix, it takes ~1 min for the value to be updated unfortunately.

### CODE REVIEW

File: origin/reg_status.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ type (
 // The TTL depends on the Status: For Status == StatusRegistrationError, the cache item won't expire,
 // meaning a failure registration stays in the cache, until the registration is successful.
 // For other Status, TTL is set to 5min
-var registrationsStatus = ttlcache.New(ttlcache.WithTTL[string, RegistrationStatus](5 * time.Minute))
+var registrationsStatus = ttlcache.New(ttlcache.WithTTL[string, RegistrationStatus](1 * time.Minute))
```
Comment (jhiemstrawisc) [inline origin/reg_status.go:63]: Does switching this to a 1-minute TTL negate the above comment?

**Review by jhiemstrawisc — APPROVED** [review]
One comment that might warrant a change, but otherwise LGTM. I'll approve and you can decide whether to merge as is.

File: origin/reg_status.go (hunk 1 above)
Comment (haoming29) [reply origin/reg_status.go:63]: Thanks for the catch! Fixed
