### PR TITLE
Groups fixes

### LINKED ISSUE #3044: Users that are automatically added to the origin's internal user database are given non-sensical (user)names
## Summary

As of Pelican v7.23.0-rc.2, when a user logs into an origin and a record is automatically created in the origin's internal user database, their (user)name is simply a copy of their OIDC `sub` — which is generally not readable or meaningful to a human.

Image

## Desired behavior

While there's no guarantee that the OIDC provider will provide a claim that could be used as a readable name for the user, there are a [slew of standard claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) that the origin could check for and try to use before falling back on `sub`.

Some of those claims could also be used to automatically populate additional fields (#3043).

### PR DESCRIPTION
**Pull request by patrickbrophy**
Closes #3044, #3049, #3050. This PR does the following:

1. Refactor Admin authz:
- Introduce UserIdentity struct to encapsulate user idenitifiers
- Updated CheckAdmin to verify privileges against all stable
  idenitifies. This ensures admins configured via OIDC subject retain
  access even if their display name changes

2. Fix Group Management Permissions:
- Updated AddGroupMember and RemoveGroupMember in the database layer to
  accept an isAdmin flag.
- Used isAdmin flag as an override

3. Improve OIDC username generation
- When generating a username, look up human-readable OIDC claims (name,
  email, preferred_username). We fall back to sub if necessary. This
  prevents users from being created with opaque, unfriendly identifiers
  by default

### CODE REVIEW

File: web_ui/groups.go [hunk 1]
```diff
@@ -184,15 +184,24 @@ func handleAddGroupMember(ctx *gin.Context) {
 		return
 	}
 
-	_, userId, _, err := GetUserGroups(ctx)
-	if err != nil || userId == "" {
+	user, userId, groups, err := GetUserGroups(ctx)
+	if err != nil {
```
Comment (h2zh) [inline web_ui/groups.go]: I think the `userId == ""` guard should be retained so the subsequent DB operations could have this "addedBy" attribute. Maybe if you have other reason to remove it?

**Review by h2zh — CHANGES_REQUESTED** [review]
Thanks for bringing these enhancements in, though bundling everything in one commit makes the review really time-consuming. Is it possible to break it into 3-4 commits (one for each ticket)?

I'm sure there's a better way to solve #3050. The issue says "a user's name should never appear anywhere we need a stable identifier." This PR adds stable identifiers (internal ID, OIDC sub) as supplementary fields that travel alongside the username, and uses them in a few specific places (admin checks, authz template matching). But the username remains the primary identity that flows through GetUserGroups -> ctx.Set("User") -> every handler -> every database operation. 

I don't have a perfect plan either - I'm thinking of changing the JWT sub to be the internal ID or OIDC sub, and treating username as purely display. But it would require tons of work. Maybe it would be worth to take some time to ponder and talk to Brian_s_ to hear they say.

File: web_ui/oauth2_client.go [hunk 2]
```diff
@@ -250,30 +250,51 @@ func generateUserGroupInfo(userInfo map[string]interface{}, idToken map[string]i
...
-	if !ok {
-		log.Errorln("User info endpoint did not return a value for the user claim", userClaim)
-		err = errors.New("identity provider did not return an identity for logged-in user")
-		return
+
+	var displayName string
+	// If the configured claim is "sub" (default), try to find a more human-readable username from standard claims
+	// This addresses Issue #3044 where users get non-sensical usernames like "http://cilogon.org/..."
+	if userClaim == "sub" {
+		usernameCandidates := []string{"preferred_username", "name", "nickname", "email"}
```
Comment (jhiemstrawisc) [inline web_ui/oauth2_client.go]: Would be useful to link to https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims as a way to provide breadcrumbs for future code readers as to where these values were picked from.

**Review by jhiemstrawisc — CHANGES_REQUESTED** [review]
I'm giving this a very light review, mostly for style, because I'm not at all familiar with this section of code and Howard already gave a precursory review. As much as I'd love to dive into it, the `v7.24` crunch is preventing me from getting as in-depth as I'd like.

**Review by jhiemstrawisc — APPROVED** [review]
My minor change request was taken care of, so I'm okay with this getting merged once everyone else is ready.
