### PR TITLE
Toggle origin/cache downtimes in director correctly

### LINKED ISSUE #2279: Director doesn't toggle origin/cache downtimes correctly
Pelican Version:
7.16.0-rc.0

Pelican Service:
- [ ] Client
- [ ] Plugin
- [ ] Registry
- [X] Director
- [ ] Origin
- [ ] Cache
- [ ] Other (please give the detail)

**Describe the bug**
When the Director receives the downtimes set by origin/cache along with the server ads, it doesn't update the server entry in `filteredServers` that were previously set into downtime. As a result:

- New active downtimes aren’t applied when a server is already filtered
- Expired downtimes aren’t cleared
- Servers can’t flip between “active” and “future” states

Downtimes created/modified by the Registry don't have this issue.

**To Reproduce**
Create a downtime in Origin, check it out in the Director. Then modify this downtime in Origin (e.g. change the start/end time, active->future), check the Director again.

### PR DESCRIPTION
**Pull request by h2zh**
Fix the bug that when the Director toggles the downtimes set by origin/cache, it skips re-evaluating any server that already has a filter (downtime).

Also simplify the code logics.

For example, let's say there is a downtime entry set by the Origin and propagated to the Director with server ads every minute:

> Note: "existing" means "existingFilterType", "had" means "isServerFiltered" in the code
> First ever “active” → had==false, so it sets serverFiltered.
> 
> Subsequent still-active → had==true && existing==serverFiltered, it doesn’t enter the `!had` branch, but we also don’t delete, because active==true skips the delete block.
> 
> Subsequent no longer active → active == false && had == true && existing == serverFiltered, so it falls into the delete block
> 
> Change time: Active to future downtime → active==false, so it hits the delete block (because existing==serverFiltered) and remove it.
> 
> Change time: Future to active downtime → had==false again, so it’ll set it back in filteredServers.

Closes #2279

### CODE REVIEW

File: director/director.go [hunk 1]
```diff
@@ -1169,33 +1169,36 @@ func registerServerAd(engineCtx context.Context, ctx *gin.Context, sType server_
...
 			}
 		}
-		// If the server doesn't have an active downtime, it means Director's previously
-		// recorded downtime set by the server admin is stale and should be removed.
-		// It only removes the downtime set by the server admin, not the downtime set by others.
-		if !bringItDown {
-			if hasOriginalFilter && originalFilterType == serverFiltered {
+
+		// Inspect the existing downtime status for this server
+		existing, had := filteredServers[sn]
```
Comment (CannonLock) [inline director/director.go:1189]: Can you update the variable names to be more informative? I had to look in the code to figure out what values to expect here.

existingFilterType, serverIsFiltered would make it so you wouldn't need the comments.

**Review by CannonLock — CHANGES_REQUESTED** [review]
Can you note for me the precedence of downtimes?

I assume Topo/Registry > Topo/Registry > ServerAds where ServerAds has the lowest precedence?

I want to double check that this precedence is enforced in the other locations.

**Comment by h2zh** [comment]
@CannonLock At this moment the precedence is ... whoever set the downtime first. For example, if server A is set to downtime by the server admin, and later the Registry also sets this server to downtime, the Director will show both downtime details, but the reason (`filteredType` in json) will stick to whoever sets the downtime first ("Temporarily disabled by the server admin"). 

If the downtime period set by the server admin ends, but the time is still in the downtime period set by the Registry, the Director will still consider this server is in downtime (`filtered: true` in json) and the reason will switch to `filteredType: Temporarily disabled via the admin website`.

File: director/director.go (hunk 1 above)
Comment (h2zh) [reply director/director.go]: Done. Thanks for the advice!

**Review by CannonLock — APPROVED** [review]
