### PR TITLE
Fixup merging of authfiles

### LINKED ISSUE #567: Cache authfile generation doesn't correctly merge existing authfile
I'm trying to use an authfile downloaded from topology (URL: https://topology.opensciencegrid.org/cache/Authfile-public?fqdn=sc-cache.chtc.wisc.edu ) which looks like
```
u * /user/ligo -rl \
    /Gluex rl \
    /NSG/PUBLIC rl \
    /VDC/PUBLIC rl \
    /chtc/PUBLIC rl \
    /chtc/itb/helm-origin/PUBLIC rl \
    /data.lhncbc.nlm.nih.gov/public rl \
    /eic rl \
    /et-gw/PUBLIC rl \
    /gluex rl \
    /gwdata rl \
    /hcc/PUBLIC rl \
    /icecube/PUBLIC rl \
    /jlab rl \
    /nrp rl \
    /osdftest rl \
    /osgconnect/collab rl \
    /osgconnect/public rl \
    /ospool/uc-shared/public rl \
    /pnfs/fnal.gov rl \
    /ucsd/physics rl \
    /uhawaii/its rl \
    /uhawaii/koa/public rl \
    /uhawaii/manoa/ifa rl \
    /user rl \
    /xenon/PUBLIC rl
```
I pointed the `Xrootd.Authfile` config knob at a copy of this file. The generated authfile at `/run/pelican/xrootd/cache/authfile-generated` is just
```
u * /user/ligo -rl \
```
with no newline at the end. This is not syntactically correct and xrootd fails to start.

### LINKED ISSUE #568: Origin authfile generation not working
I have an authfile from topology for one of my origins ( https://topology.opensciencegrid.org/origin/Authfile?fqdn=sc-origin.chtc.wisc.edu ) that I'm trying to use; I downloaded it and pointed the `Xrootd.Authfile` option at it. It looks like
```
# DN: /CN=sc-origin.chtc.wisc.edu
u 5a42185a.0 /chtc/PROTECTED/sc-origin lr
# DN: /DC=org/DC=incommon/C=US/ST=California/O=University of California, San Diego/CN=osg-stash-sfu-computecanada-ca.nationalresearchplatform.org
u 4ff08838.0 /chtc/PROTECTED/sc-origin lr
# DN: /DC=org/DC=incommon/C=US/ST=Georgia/O=Georgia Institute of Technology/OU=Office of Information Technology/CN=osg-gftp2.pace.gatech.edu
u 3af6a420.0 /chtc/PROTECTED/sc-origin lr
```
and so on.

The generated authfile just looks like
```
u * /.well-known lr
```
which means I can't access any of the files under `/chtc/PROTECTED/sc-origin`.

### PR DESCRIPTION
**Pull request by bbockelm**
The first commit handles line continuation characters, allowing the current syntax generated by topology to be used.

The second commit ensures we merge in lines that _aren't_ public lines.  This is needed for VOMS/X509-based authentication.

Fixes #567 
Fixes #568

### CODE REVIEW

**Comment by bbockelm** [comment]
@matyasselmeci - this is the PR for fixing the authfile generation.

File: xrootd/authorization.go [hunk 1]
```diff
@@ -138,31 +201,36 @@ func EmitScitokensConfiguration(modules config.ServerType, cfg *ScitokensCfg) er
...
 	foundPublicLine := false
+	log.Debugln("Parsing the input authfile")
 	for sc.Scan() {
 		lineContents := sc.Text()
 		words := strings.Fields(lineContents)
-		// There exists a public access already in the authfile
 		if len(words) >= 2 && words[0] == "u" && words[1] == "*" {
+			// There exists a public access already in the authfile
 			if server.GetServerType().IsEnabled(config.OriginType) {
 				// If Origin, add the ./well-known to the authfile
```
Comment (matyasselmeci) [inline xrootd/authorization.go:221]:
```suggestion
				// If Origin, add the /.well-known to the authfile
```

**Review by matyasselmeci — APPROVED** [review]
LGTM but what happens if `/.well-known` is already in the authfile?

**Comment by bbockelm** [comment]
I tested it -- there didn't seem to be an issue with the duplicated `/.well-known` (at least as far as xrootd startup is concerned).  It's a bit of an eyesore -- but I didn't worry too much given it's an auto-generated file.
