### PR TITLE
Fix isProxyEnabled()

### LINKED ISSUE #2371: disableHTTPProxy isn't really being considered
It seems we are always turning off the HTTP or HTTPS Proxy regardless of whether disableHTTPProxy is set.

This should be fixed to only be disabled when the parameter is set.

We should also determined if we want a separate disableHTTPSProxy parameter or if the same parameter should handle all proxies (and then potentially be renamed?)

### PR DESCRIPTION
**Pull request by turetske**
-- Checks Client_DisableHttpProxy first
-- Also now checks all 4 standar env vars
-- Creates tests to ensure proper handling

Closes #2371

### CODE REVIEW

File: client/handle_http.go [hunk 1]
```diff
@@ -588,13 +588,15 @@ func mergeCancel(ctx1, ctx2 context.Context) (context.Context, context.CancelFun
...
 func isProxyEnabled() bool {
-	if _, isSet := os.LookupEnv("http_proxy"); !isSet {
-		return false
-	}
 	if param.Client_DisableHttpProxy.GetBool() {
 		return false
 	}
-	return true
+	for _, envVar := range []string{"http_proxy", "HTTP_PROXY", "https_proxy", "HTTPS_PROXY"} {
+		if _, isSet := os.LookupEnv(envVar); isSet {
```
Comment (h2zh) [inline client/handle_http.go]: Do we need to consider these variable is set to an empty string?
